### ISSUE TITLE
Querk while using StringTagField in SiteConfig Extensions

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-tagfield#118] opened 2018-09-18 22:05 UTC
I am using the `StringTagField` in SiteConfig extension like below:
`StringTagField::create('Emails', 'Emails', explode(',', $this->owner->Emails), explode(',', $this->owner->Emails))`

While saving it, the tags does not appear immediately on the field. I had to do a full refresh in order to see the tags.

**Comment by robbieaverill** [comment] 2018-09-19 09:01
Can you please provide the versions of tagfield and the CMS that you're using?

**Comment by robbieaverill** [comment] 2018-09-22 13:32
Hi @pxwee5, I've just tried to reproduce your issue on SilverStripe 4.2.1 using the [example usage for StringTagField](https://github.com/silverstripe/silverstripe-tagfield/blob/master/docs/en/using.md) and I don't see your issue.

In your example you're using `explode(',', $this->owner->Emails)` as both the third and fourth argument for StringTagField. The third argument should be a source list, and the fourth should be the values for the field. It's possible that you're experiencing strange behaviour because you're defining the source list as the options you've already saved for the field. 

Please feel free to reopen if you would like to =) Thanks for reporting.

**Comment by robbieaverill** [comment] 2018-09-24 10:27
@pxwee5 this is my test code:

```php
# File: app/src/TestExtension.php
<?php

use SilverStripe\Forms\FieldList;
use SilverStripe\ORM\DataExtension;
use SilverStripe\TagField\StringTagField;

class TestExtension extends DataExtension
{
    private static $db = ['Title' => 'Varchar'];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldToTab(
            'Root.Main',
            StringTagField::create(
                'Title',
                'Title',
                array('one', 'two'),
                explode(',', $this->owner->Title)
            )
        );
    }
}
```

```
# File: app/_config/temp.yml
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - TestExtension

```

**Comment by pxwee5** [comment] 2018-09-24 23:29
Can it be done so that I can add titles dynamically instead of using a fixed array? Like so?
```
public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldToTab(
            'Root.Main',
            StringTagField::create(
                'Title',
                'Title',
                explode(',', $this->owner->Title),
                explode(',', $this->owner->Title)
            )
        );
    }
```

**Comment by robbieaverill** [comment] 2018-09-25 09:42
Yes the source can be dynamic, but in your example you're only allowing the user to choose from values they've already selected - this seems wrong to me

**Comment by pxwee5** [comment] 2018-10-01 22:33
@robbieaverill I tested this again this morning, and I realised that
1. The `source` and `values` determine the options displayed on the field based on`in_array($source, $values)`. So if I don't set both source and value to `explode(',', $this->owner->Title)`, nothing will show on the field. 
2. The only way to display them is to set it as the same. However, there's a bug after save where the latest value will not show until I refresh the page. 

You can replicate it by:
1. Create a StringTagField: `. StringTagField::create('Title', 'Title', explode(',', $this->owner->Title), explode(',', $this->owner->Title))
2. Make your own tags: `Tag1`, `Tag2` then save. 
3. You will notice immediately that after you save, the field shows nothing. But the values are saved into the database as `Tag1, Tag2`
4. Refresh and then `Tag1`, `Tag2` will appear on the StringTagField.

**Comment by robbieaverill** [comment] 2018-10-01 22:34
@pxwee5

**Comment by robbieaverill** [comment] 2018-11-15 19:40
@pxwee5 sorry about the delay, I'm just looking at this now while fixing a bug in the other TagField class. It looks like StringTagField is totally broken. I'll fix it now.

**Comment by robbieaverill** [comment] 2018-11-15 21:02
@pxwee5 PR at #122 which should fix your problem

**Comment by robbieaverill** [comment] 2019-02-22 06:16
#122 is merged now, feel free to reopen if you're still having problems with this =)

**Closed by robbieaverill** 2019-02-22 06:16 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug
