### ISSUE TITLE
StringTagField should not write record in saveInto

### ISSUE THREAD

**Issue by iqmeckert** [silverstripe/silverstripe-tagfield#119] opened 2018-09-19 12:27 UTC
In class StringTagField, the method saveInto() should not write the data record. Validation will take place before all values are pushed to the DataObject, therefore throwing false validation errors.

Also, should remove empty values or zeros when used as "not multiple"

**Comment by robbieaverill** [comment] 2018-09-19 14:13
Which version are you using please?

**Comment by iqmeckert** [comment] 2018-09-19 16:12
According to the changelog, I'm using version 1.3.0 in SS 4.1.2, but I see the code is the same in the latest version. I'm using StringTagField because the field I'm setting is on the same record, where it looks like TagField requires a relational object

**Comment by robbieaverill** [comment] 2018-11-15 19:34
I think this is a duplicate of #79 - feel free to reopen if you disagree @iqmeckert =)

**Closed by robbieaverill** 2018-11-15 19:34 UTC
Labels: affects/v4, type/bug
