### ISSUE TITLE
SS4: Missing chosen-sprite.png in TagField.css

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-tagfield#102] opened 2017-10-26 07:02 UTC
TagField.css refers to `url('../../framework/admin/thirdparty/chosen/chosen/chosen-sprite.png')` which, although still exists in the admin, is no longer available via `/resources/` nor via framework.

**Comment by zanderwar** [comment] 2017-11-03 02:27
Confirmed, same issue

**Comment by tractorcow** [comment] 2017-11-03 02:42
Chosen has been shifted to admin now, but the image is only in the non-exposed admin/client/src/images folder.

We should move that to dist and make sure it's used by chosen dropdown in the CMS.

**Comment by tractorcow** [comment] 2017-11-03 02:44
Logged on admin module at https://github.com/silverstripe/silverstripe-admin/issues/339

**Comment by flamerohr** [comment] 2017-11-13 02:58
Pull request made which makes `chosen-sprite.png` available in admin's dist folder :)
Reference on here will need to be updated to match

**Comment by tractorcow** [comment] 2017-11-13 22:08
Ok, it's public now https://github.com/silverstripe/silverstripe-admin/pull/353

Need to update this module with the new path.

**Comment by robbieaverill** [comment] 2018-07-13 01:56
I'm going to close this since we're going to be replacing the tag field rendering with a React based equivalent which will be controlled by the admin module in terms of styling/design. Doing that would make this issue obsolete. Since that issue is in progress at #110, doing this would be wasted effort.

**Closed by robbieaverill** 2018-07-13 01:56 UTC
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug
