### ISSUE TITLE
Impossible to select tags in 1.3.3

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-tagfield#141] opened 2019-04-15 04:52 UTC
I have experienced this same issue on two completely separate SS3 sites, where the update to 1.3.3 prevents any tags from being added when the field is initially empty. The dropdown tag selector is completely empty.

If there is at least one tag already in the tagfield then it works as expected, just not when the initial value is empty.

Downgrading to 1.3.2 fixed it on both occasions. I'm not doing anything fancy, just something like:
```
TagField::create(
    'Locations',
    'Location / Branch',
    LocationsPage::get(),
    $this->Locations()
)
```

**Comment by robbieaverill** [comment] 2019-04-15 04:53
Do you have anything in the console?

**Comment by axllent** [comment] 2019-04-15 04:57
Sorry, I should have mentioned that. No JS errors. I just get "no results found" (when I know there are results :))

![Screenshot from 2019-04-15 16-55-29](https://user-images.githubusercontent.com/1463435/56108318-69254600-5f9f-11e9-8183-b003c5f9b62c.png)

**Comment by robbieaverill** [comment] 2019-04-15 05:06
Thanks. So there's a regression in the SilverStripe 3 version of this module between 1.3.2 and 1.3.3, which is good to know. SilverStripe 3 is in limited support, but since this is a pretty critical bug I'll leave it open. Good to know you can use 1.3.2 to work around the issue for now.

**Comment by wilr** [comment] 2021-12-18 23:12
Closing since SS3 is EOL

**Closed by wilr** 2021-12-18 23:12 UTC
Labels: affects/v3, change/patch, effort/medium, impact/high, type/bug
